# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' FLS fit
#'
#' This function is used to fit Time-Varying Linear Regression via Flexible least squares (FLS) as discribed in R. Kalaba and L. Tesfatsion (1989).
#'
#' @param X design matrix of dimensuin \eqn{n * K}.
#' @param y vector of observations of length \eqn{n}.
#' @param mu parameter controling relative weight of sum of dynamic errors (\eqn{r_D^2}) vs sums of squared residual measurement errors (\eqn{r_M^2}).
#' @param smooth logical. If TRUE, a smoothed estimate is provided.
#' @return A \eqn{n * K} matrix coefficient estimates.
#' @references
#' \insertRef{KALABA19891215}{fls}
#'
#' @export
fls.fit <- function(X, y, mu, smooth = FALSE) {
    .Call(`_fls_rcpp_FLS`, X, y, mu, smooth)
}

