# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.rcpp_FLS <- function(X, y, mu, smooth = FALSE) {
    .Call(`_FastFLS_rcpp_FLS`, X, y, mu, smooth)
}

